apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: ogavrylenko/hello-gitops
  newTag: fedefb4ae4c2ff66928cf467e7dcc74040d98dac
