apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-green
images:
- name: hello-gitops
  newName: ogavrylenko/hello-gitops
  newTag: 06dccee5090aaba32017986d265e9bf311d7ec87
